/**
 * signatures 테이블 스키마 마이그레이션 스크립트
 * 사용법: npx tsx scripts/migrate-signatures-schema.ts
 */

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://titqtnobfapyjvairgqy.supabase.co'
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdHF0bm9iZmFweWp2YWlyZ3F5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODc5NDQyNSwiZXhwIjoyMDg0MzcwNDI1fQ.M6mlPiqgRruYCd4jXBcIOsYIhtqgvJmGmzg6l3KakwU'

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { persistSession: false }
})

async function checkCurrentSchema() {
  console.log('📋 현재 signatures 테이블 스키마 확인...')

  // 빈 데이터 하나 select해서 컬럼 확인
  const { data, error } = await supabase
    .from('signatures')
    .select('*')
    .limit(1)

  if (error) {
    console.log('❌ 테이블 조회 실패:', error.message)
    return null
  }

  // 컬럼 목록 확인을 위해 전체 테이블 정보 조회
  console.log('현재 데이터 샘플:', data)
  return data
}

async function main() {
  console.log('🚀 signatures 테이블 스키마 마이그레이션')
  console.log('')

  await checkCurrentSchema()

  // 방법: RPC를 통해 SQL 실행 (exec_sql 함수가 있어야 함)
  // 또는: Supabase Dashboard에서 직접 SQL 실행

  console.log('')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log('📝 다음 SQL을 Supabase SQL Editor에서 실행하세요:')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log(`
-- 1. 기존 테이블 백업
CREATE TABLE IF NOT EXISTS signatures_backup AS SELECT * FROM signatures;

-- 2. 기존 테이블 삭제
DROP TABLE IF EXISTS public.signatures CASCADE;

-- 3. 새 signatures 테이블 생성
CREATE TABLE public.signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sig_number integer NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  unit public.org_unit NOT NULL DEFAULT 'excel',
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number)
);

-- 4. RLS 설정
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "signatures_read_all" ON public.signatures
  FOR SELECT USING (true);

CREATE POLICY "signatures_insert_admin" ON public.signatures
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- 5. 인덱스 생성
CREATE INDEX idx_signatures_unit ON public.signatures(unit);
CREATE INDEX idx_signatures_sig_number ON public.signatures(sig_number);
`)
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
}

main().catch(console.error)
