-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Create Enums (implied in TS types)
create type public.user_role as enum ('member', 'vip', 'moderator', 'admin', 'superadmin');
create type public.org_unit as enum ('excel', 'crew');

-- 1. Profiles Table (Extends auth.users)
create table public.profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  nickname text not null,
  email text,
  avatar_url text,
  role public.user_role default 'member'::public.user_role not null,
  unit public.org_unit,
  total_donation bigint default 0,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 2. Seasons Table
create table public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date,
  is_active boolean default false not null,
  created_at timestamptz default now() not null
);

-- 3. Organization Table (Recursive)
create table public.organization (
  id bigint generated by default as identity primary key,
  unit public.org_unit not null,
  profile_id uuid references public.profiles(id),
  name text not null,
  role text not null, -- Display role title like "Team Leader"
  position_order int default 0 not null,
  parent_id bigint references public.organization(id),
  image_url text,
  social_links jsonb,
  is_live boolean default false not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null
);

-- 4. Donations Table
create table public.donations (
  id bigint generated by default as identity primary key,
  donor_id uuid references public.profiles(id),
  donor_name text not null, -- In case of anonymous/external donors
  amount bigint not null,
  season_id bigint references public.seasons(id) not null,
  unit public.org_unit,
  message text,
  created_at timestamptz default now() not null
);

-- 5. VIP Rewards
create table public.vip_rewards (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) not null,
  season_id bigint references public.seasons(id) not null,
  rank int not null,
  personal_message text,
  dedication_video_url text,
  created_at timestamptz default now() not null
);

-- 6. VIP Images (One-to-Many with Rewards)
create table public.vip_images (
  id bigint generated by default as identity primary key,
  reward_id bigint references public.vip_rewards(id) on delete cascade not null,
  image_url text not null,
  title text,
  order_index int default 0 not null,
  created_at timestamptz default now() not null
);

-- 7. Signatures (Gallery/Media)
create table public.signatures (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  unit public.org_unit not null,
  member_name text not null,
  media_type text check (media_type in ('video', 'image', 'gif')) not null,
  media_url text not null,
  thumbnail_url text,
  tags text[],
  view_count bigint default 0 not null,
  is_featured boolean default false not null,
  created_at timestamptz default now() not null
);

-- 8. Schedules
create table public.schedules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  unit public.org_unit,
  event_type text check (event_type in ('broadcast', 'collab', 'event', 'notice', '休')) not null,
  start_datetime timestamptz not null,
  end_datetime timestamptz,
  location text,
  is_all_day boolean default false not null,
  color text,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now() not null
);

-- 9. Timeline Events
create table public.timeline_events (
  id bigint generated by default as identity primary key,
  event_date date not null,
  title text not null,
  description text,
  image_url text,
  category text,
  season_id bigint references public.seasons(id),
  order_index int default 0,
  created_at timestamptz default now() not null
);

-- 10. Notices
create table public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text check (category in ('official', 'excel', 'crew')) not null,
  thumbnail_url text,
  is_pinned boolean default false not null,
  view_count bigint default 0 not null,
  author_id uuid references public.profiles(id),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 11. Posts (Community)
create table public.posts (
  id bigint generated by default as identity primary key,
  board_type text check (board_type in ('free', 'vip')) not null,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) not null,
  view_count bigint default 0 not null,
  like_count bigint default 0 not null,
  comment_count bigint default 0 not null,
  is_anonymous boolean default false not null,
  is_deleted boolean default false not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 12. Comments
create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) not null,
  content text not null,
  parent_id bigint references public.comments(id),
  is_deleted boolean default false not null,
  created_at timestamptz default now() not null
);

-- 13. Media Content (Shorts/VODs)
create table public.media_content (
  id bigint generated by default as identity primary key,
  content_type text check (content_type in ('shorts', 'vod')) not null,
  title text not null,
  description text,
  thumbnail_url text,
  video_url text not null,
  unit public.org_unit,
  duration int,
  view_count bigint default 0 not null,
  is_featured boolean default false not null,
  created_at timestamptz default now() not null
);

-- 14. Live Status
create table public.live_status (
  id bigint generated by default as identity primary key,
  member_id bigint references public.organization(id) not null,
  platform text check (platform in ('chzzk', 'twitch', 'youtube', 'pandatv')) not null,
  stream_url text not null,
  thumbnail_url text,
  is_live boolean default false not null,
  viewer_count int default 0 not null,
  last_checked timestamptz default now() not null
);

-- 15. Banners (already existed in previous migration, but included for completeness if fresh init)
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  link_url text,
  display_order int default 0 not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Helper function to update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Apply updated_at triggers
create trigger handle_updated_at before update on public.profiles
  for each row execute procedure public.handle_updated_at();

create trigger handle_updated_at before update on public.notices
  for each row execute procedure public.handle_updated_at();

create trigger handle_updated_at before update on public.posts
  for each row execute procedure public.handle_updated_at();

create trigger handle_updated_at before update on public.banners
  for each row execute procedure public.handle_updated_at();

-- Helper function to update donation totals
create or replace function public.update_donation_total()
returns trigger as $$
begin
  if (TG_OP = 'INSERT') then
    if (NEW.donor_id is not null) then
      update public.profiles
      set total_donation = total_donation + NEW.amount
      where id = NEW.donor_id;
    end if;
  elsif (TG_OP = 'DELETE') then
    if (OLD.donor_id is not null) then
      update public.profiles
      set total_donation = total_donation - OLD.amount
      where id = OLD.donor_id;
    end if;
  elsif (TG_OP = 'UPDATE') then
    if (OLD.donor_id is not null) then
      update public.profiles
      set total_donation = total_donation - OLD.amount
      where id = OLD.donor_id;
    end if;
    if (NEW.donor_id is not null) then
      update public.profiles
      set total_donation = total_donation + NEW.amount
      where id = NEW.donor_id;
    end if;
  end if;
  return null;
end;
$$ language plpgsql security definer;

create trigger on_donation_change
  after insert or update or delete on public.donations
  for each row execute procedure public.update_donation_total();

-- Row Level Security (RLS)
-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.seasons enable row level security;
alter table public.organization enable row level security;
alter table public.donations enable row level security;
alter table public.vip_rewards enable row level security;
alter table public.vip_images enable row level security;
alter table public.signatures enable row level security;
alter table public.schedules enable row level security;
alter table public.timeline_events enable row level security;
alter table public.notices enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.media_content enable row level security;
alter table public.live_status enable row level security;
alter table public.banners enable row level security;

-- Policies (Simplified for Dev/MVP)

-- Profiles: Public read, User update own
create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using (true);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Public Data (Read Only for everyone, Admin Write)
-- (Assuming Admin has role 'admin' or 'superadmin' in profiles, 
--  but for RLS simplest is just service_role or specific user check. 
--  Sticking to "Everyone can read" for now for public pages)

create policy "Seasons are viewable by everyone" on public.seasons for select using (true);
create policy "Organization is viewable by everyone" on public.organization for select using (true);
create policy "Donations are viewable by everyone" on public.donations for select using (true);
create policy "VIP Rewards are viewable by everyone" on public.vip_rewards for select using (true);
create policy "VIP Images are viewable by everyone" on public.vip_images for select using (true);
create policy "Signatures are viewable by everyone" on public.signatures for select using (true);
create policy "Schedules are viewable by everyone" on public.schedules for select using (true);
create policy "Timeline events are viewable by everyone" on public.timeline_events for select using (true);
create policy "Notices are viewable by everyone" on public.notices for select using (true);
create policy "Media content is viewable by everyone" on public.media_content for select using (true);
create policy "Live status is viewable by everyone" on public.live_status for select using (true);
create policy "Banners are viewable by everyone" on public.banners for select using (true);

-- Posts & Comments
create policy "Posts are viewable by everyone" on public.posts for select using (true);
create policy "Authenticated users can create posts" on public.posts for insert with check (auth.uid() = author_id);
create policy "Users can update own posts" on public.posts for update using (auth.uid() = author_id);
create policy "Users can delete own posts" on public.posts for delete using (auth.uid() = author_id);

create policy "Comments are viewable by everyone" on public.comments for select using (true);
create policy "Authenticated users can create comments" on public.comments for insert with check (auth.uid() = author_id);
create policy "Users can update own comments" on public.comments for update using (auth.uid() = author_id);
create policy "Users can delete own comments" on public.comments for delete using (auth.uid() = author_id);
