-- =====================================================
-- 스키마 동기화 마이그레이션
-- database.ts 타입 정의와 실제 Supabase 테이블 동기화
-- 실행일: 2026-01-21
-- =====================================================

-- =============================================================
-- 1. vip_personal_messages 테이블 생성
-- VIP 본인이 자신의 페이지에 남기는 메시지 (사진/글/영상)
-- =============================================================

CREATE TABLE IF NOT EXISTS public.vip_personal_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  message_type text NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'image', 'video')),
  content_text text CHECK (char_length(content_text) <= 2000),
  content_url text,  -- 이미지 URL 또는 영상 외부 링크
  is_public boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_vip_personal_messages_vip_profile
  ON public.vip_personal_messages(vip_profile_id);
CREATE INDEX IF NOT EXISTS idx_vip_personal_messages_author
  ON public.vip_personal_messages(author_id);
CREATE INDEX IF NOT EXISTS idx_vip_personal_messages_created
  ON public.vip_personal_messages(created_at DESC);

-- 코멘트 추가
COMMENT ON TABLE public.vip_personal_messages IS 'VIP 본인이 자신의 개인 페이지에 남기는 메시지';
COMMENT ON COLUMN public.vip_personal_messages.vip_profile_id IS '메시지가 표시되는 VIP 페이지 소유자 ID';
COMMENT ON COLUMN public.vip_personal_messages.author_id IS '메시지 작성자 ID (VIP 본인)';
COMMENT ON COLUMN public.vip_personal_messages.message_type IS '메시지 타입: text, image, video';
COMMENT ON COLUMN public.vip_personal_messages.content_text IS '텍스트 메시지 (최대 2000자)';
COMMENT ON COLUMN public.vip_personal_messages.content_url IS '이미지 URL 또는 영상 외부 링크';
COMMENT ON COLUMN public.vip_personal_messages.is_public IS '공개 여부';

-- updated_at 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_vip_personal_message_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS vip_personal_message_updated_at ON public.vip_personal_messages;
CREATE TRIGGER vip_personal_message_updated_at
  BEFORE UPDATE ON public.vip_personal_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_vip_personal_message_updated_at();

-- RLS 활성화
ALTER TABLE public.vip_personal_messages ENABLE ROW LEVEL SECURITY;

-- SELECT: 공개 메시지는 모두 조회 가능, 비공개는 VIP 본인/관리자만
CREATE POLICY "vip_personal_messages_select"
  ON public.vip_personal_messages
  FOR SELECT
  USING (
    is_deleted = false
    AND (
      is_public = true
      OR auth.uid() = vip_profile_id
      OR auth.uid() = author_id
      OR is_admin(auth.uid())
    )
  );

-- INSERT: VIP 본인만 자기 페이지에 작성 가능
CREATE POLICY "vip_personal_messages_insert"
  ON public.vip_personal_messages
  FOR INSERT
  WITH CHECK (
    auth.uid() = vip_profile_id
    AND auth.uid() = author_id
  );

-- UPDATE: 작성자 본인 또는 관리자만 수정 가능
CREATE POLICY "vip_personal_messages_update"
  ON public.vip_personal_messages
  FOR UPDATE
  USING (
    auth.uid() = author_id
    OR is_admin(auth.uid())
  );

-- DELETE: 작성자 본인 또는 관리자만 삭제 가능
CREATE POLICY "vip_personal_messages_delete"
  ON public.vip_personal_messages
  FOR DELETE
  USING (
    auth.uid() = author_id
    OR is_admin(auth.uid())
  );

-- =============================================================
-- 2. organization.current_rank 컬럼 추가
-- 직급전 현재 직급 (대표는 null)
-- =============================================================

ALTER TABLE public.organization
ADD COLUMN IF NOT EXISTS current_rank VARCHAR(50) DEFAULT NULL;

COMMENT ON COLUMN public.organization.current_rank IS '직급전 현재 직급 (대표는 null)';

-- =============================================================
-- 3. episodes 컬럼 추가 (is_finalized, finalized_at)
-- 회차 확정 여부 및 확정 시간
-- =============================================================

ALTER TABLE public.episodes
ADD COLUMN IF NOT EXISTS is_finalized boolean DEFAULT false;

ALTER TABLE public.episodes
ADD COLUMN IF NOT EXISTS finalized_at timestamptz DEFAULT NULL;

COMMENT ON COLUMN public.episodes.is_finalized IS '회차 후원 집계 확정 여부';
COMMENT ON COLUMN public.episodes.finalized_at IS '회차 확정 시간';

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_episodes_finalized
  ON public.episodes(is_finalized)
  WHERE is_finalized = true;

-- =============================================================
-- 4. vip_rewards.episode_id 컬럼 추가
-- 회차별 VIP 보상 연결
-- =============================================================

ALTER TABLE public.vip_rewards
ADD COLUMN IF NOT EXISTS episode_id bigint REFERENCES episodes(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.vip_rewards.episode_id IS '연결된 회차 ID (회차별 VIP 보상인 경우)';

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_vip_rewards_episode
  ON public.vip_rewards(episode_id);

-- =============================================================
-- 완료!
-- =============================================================

DO $$
BEGIN
  RAISE NOTICE '스키마 동기화 완료!';
  RAISE NOTICE '- vip_personal_messages 테이블 생성';
  RAISE NOTICE '- organization.current_rank 컬럼 추가';
  RAISE NOTICE '- episodes.is_finalized, finalized_at 컬럼 추가';
  RAISE NOTICE '- vip_rewards.episode_id 컬럼 추가';
END $$;
