-- ============================================
-- BJ 감사 메시지 테이블
-- VIP 후원자에게 BJ 멤버들이 남기는 개인 메시지
-- ============================================

-- 테이블 생성
CREATE TABLE public.bj_thank_you_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  bj_member_id bigint NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
  message_type text NOT NULL CHECK (message_type IN ('text', 'image', 'video')),
  content_text text CHECK (char_length(content_text) <= 1000),
  content_url text,  -- 이미지 URL 또는 영상 외부 링크 (YouTube, Google Drive 등)
  is_public boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 인덱스 생성
CREATE INDEX idx_bj_messages_vip_profile ON public.bj_thank_you_messages(vip_profile_id);
CREATE INDEX idx_bj_messages_bj_member ON public.bj_thank_you_messages(bj_member_id);
CREATE INDEX idx_bj_messages_created ON public.bj_thank_you_messages(created_at DESC);

-- 코멘트 추가
COMMENT ON TABLE public.bj_thank_you_messages IS 'BJ 멤버들이 VIP 후원자에게 남기는 감사 메시지';
COMMENT ON COLUMN public.bj_thank_you_messages.vip_profile_id IS '메시지를 받는 VIP 후원자 ID';
COMMENT ON COLUMN public.bj_thank_you_messages.bj_member_id IS '메시지를 작성한 BJ 멤버 ID (organization 테이블)';
COMMENT ON COLUMN public.bj_thank_you_messages.message_type IS '메시지 타입: text, image, video';
COMMENT ON COLUMN public.bj_thank_you_messages.content_text IS '텍스트 메시지 (최대 1000자)';
COMMENT ON COLUMN public.bj_thank_you_messages.content_url IS '이미지 URL 또는 영상 외부 링크';
COMMENT ON COLUMN public.bj_thank_you_messages.is_public IS '공개 여부: true=전체 공개, false=VIP/작성자/관리자 전용';

-- ============================================
-- 헬퍼 함수
-- ============================================

-- BJ 멤버인지 확인하는 함수
CREATE OR REPLACE FUNCTION is_bj_member(user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.organization
    WHERE profile_id = user_id
    AND is_active = true
  );
END;
$$;

-- 사용자의 BJ 멤버 ID 조회 함수
CREATE OR REPLACE FUNCTION get_bj_member_id(user_id uuid)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  member_id bigint;
BEGIN
  SELECT id INTO member_id
  FROM public.organization
  WHERE profile_id = user_id
  AND is_active = true
  LIMIT 1;

  RETURN member_id;
END;
$$;

-- updated_at 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_bj_message_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER bj_message_updated_at
  BEFORE UPDATE ON public.bj_thank_you_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_bj_message_updated_at();

-- ============================================
-- RLS 정책
-- ============================================

-- RLS 활성화
ALTER TABLE public.bj_thank_you_messages ENABLE ROW LEVEL SECURITY;

-- SELECT: 로그인 사용자 중 공개 메시지는 모두 조회 가능, 비공개는 VIP/작성자/관리자만
CREATE POLICY "VIP 본인 또는 관리자만 조회 가능"
  ON public.bj_thank_you_messages
  FOR SELECT
  USING (
    is_deleted = false
    AND auth.uid() IS NOT NULL
    AND (
      is_public
      OR auth.uid() = vip_profile_id
      OR is_admin(auth.uid())
      OR EXISTS (
        SELECT 1 FROM public.organization
        WHERE id = bj_member_id
          AND profile_id = auth.uid()
          AND is_active = true
      )
    )
  );

-- INSERT: organization.profile_id가 일치하는 BJ만 작성 가능
CREATE POLICY "BJ 멤버만 작성 가능"
  ON public.bj_thank_you_messages
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.organization
      WHERE id = bj_member_id
      AND profile_id = auth.uid()
      AND is_active = true
    )
  );

-- UPDATE: 작성자 본인 또는 관리자만 수정 가능
CREATE POLICY "작성자 또는 관리자만 수정 가능"
  ON public.bj_thank_you_messages
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.organization
      WHERE id = bj_member_id
      AND profile_id = auth.uid()
      AND is_active = true
    )
    OR is_admin(auth.uid())
  );

-- DELETE: 작성자 본인 또는 관리자만 삭제 가능 (soft delete 권장)
CREATE POLICY "작성자 또는 관리자만 삭제 가능"
  ON public.bj_thank_you_messages
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.organization
      WHERE id = bj_member_id
      AND profile_id = auth.uid()
      AND is_active = true
    )
    OR is_admin(auth.uid())
  );
