-- 시그니처 시스템 재설계 마이그레이션
-- 기존: 시그니처 1개 = 멤버 1명의 영상 1개
-- 변경: 시그니처 = 시그번호별 리액션 정의, 멤버별 영상은 별도 테이블

-- =====================================================
-- 1. 기존 signatures 테이블 백업 (필요시)
-- =====================================================
-- CREATE TABLE IF NOT EXISTS public.signatures_backup AS SELECT * FROM public.signatures;

-- =====================================================
-- 2. signatures 테이블 재설계
-- =====================================================

-- 기존 컬럼 제거 및 새 컬럼 추가
ALTER TABLE public.signatures
  DROP COLUMN IF EXISTS member_name,
  DROP COLUMN IF EXISTS media_type,
  DROP COLUMN IF EXISTS media_url,
  DROP COLUMN IF EXISTS tags,
  DROP COLUMN IF EXISTS view_count,
  DROP COLUMN IF EXISTS is_featured;

-- 새 컬럼 추가
ALTER TABLE public.signatures
  ADD COLUMN IF NOT EXISTS sig_number integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_group boolean DEFAULT false NOT NULL;

-- 부서 내 시그번호 중복 방지 제약조건
ALTER TABLE public.signatures
  DROP CONSTRAINT IF EXISTS signatures_unit_sig_number_unique;
ALTER TABLE public.signatures
  ADD CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number);

-- 인덱스 업데이트
DROP INDEX IF EXISTS idx_signatures_member;
DROP INDEX IF EXISTS idx_signatures_featured;
CREATE INDEX IF NOT EXISTS idx_signatures_sig_number ON public.signatures(sig_number);
CREATE INDEX IF NOT EXISTS idx_signatures_is_group ON public.signatures(is_group);

-- =====================================================
-- 3. signature_videos 테이블 생성
-- =====================================================
CREATE TABLE IF NOT EXISTS public.signature_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signature_id bigint NOT NULL REFERENCES public.signatures(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.organization(id) ON DELETE CASCADE,
  video_url text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(signature_id, member_id)
);

COMMENT ON TABLE public.signature_videos IS '시그니처별 멤버 영상';
COMMENT ON COLUMN public.signature_videos.signature_id IS '시그니처 ID';
COMMENT ON COLUMN public.signature_videos.member_id IS '조직도 멤버 ID';
COMMENT ON COLUMN public.signature_videos.video_url IS '영상 URL';

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_signature_videos_signature ON public.signature_videos(signature_id);
CREATE INDEX IF NOT EXISTS idx_signature_videos_member ON public.signature_videos(member_id);

-- =====================================================
-- 4. RLS 정책
-- =====================================================
ALTER TABLE public.signature_videos ENABLE ROW LEVEL SECURITY;

-- 모든 사용자 읽기 가능
DROP POLICY IF EXISTS "Signature videos are viewable by everyone" ON public.signature_videos;
CREATE POLICY "Signature videos are viewable by everyone"
  ON public.signature_videos FOR SELECT USING (true);

-- 관리자만 CRUD 가능
DROP POLICY IF EXISTS "Staff can manage signature videos" ON public.signature_videos;
CREATE POLICY "Staff can manage signature videos"
  ON public.signature_videos FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'superadmin', 'moderator')
    )
  );

-- =====================================================
-- 5. 테이블 코멘트 업데이트
-- =====================================================
COMMENT ON TABLE public.signatures IS '시그니처 (시그번호별 리액션 정의)';
COMMENT ON COLUMN public.signatures.sig_number IS '시그 번호';
COMMENT ON COLUMN public.signatures.title IS '시그 제목';
COMMENT ON COLUMN public.signatures.description IS '시그 설명';
COMMENT ON COLUMN public.signatures.thumbnail_url IS '썸네일 이미지/GIF URL';
COMMENT ON COLUMN public.signatures.unit IS '부서 (excel/crew)';
COMMENT ON COLUMN public.signatures.is_group IS '단체 시그 여부';
