-- =============================================================
-- RG Family: 완전한 데이터베이스 스키마 (2026-01-19 백업)
-- Supabase SQL Editor에서 한 번에 실행
-- =============================================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- PART 1: ENUM 타입
-- =============================================================

DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('member', 'vip', 'moderator', 'admin', 'superadmin');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.org_unit AS ENUM ('excel', 'crew');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- =============================================================
-- PART 2: 테이블 생성
-- =============================================================

-- 1. Profiles (회원 프로필)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nickname text NOT NULL,
  email text,
  avatar_url text,
  role public.user_role DEFAULT 'member'::public.user_role NOT NULL,
  unit public.org_unit,
  total_donation bigint DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. Seasons (시즌)
CREATE TABLE IF NOT EXISTS public.seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  is_active boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 3. Organization (조직도)
CREATE TABLE IF NOT EXISTS public.organization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit public.org_unit NOT NULL,
  profile_id uuid REFERENCES public.profiles(id),
  name text NOT NULL,
  role text NOT NULL,
  position_order int DEFAULT 0 NOT NULL,
  parent_id bigint REFERENCES public.organization(id),
  image_url text,
  social_links jsonb,  -- {"pandatv": "id", "youtube": "url", ...}
  profile_info jsonb,  -- {"mbti": "ENFP", "birthday": "2000-01-01", "bloodType": "A", ...}
  is_live boolean DEFAULT false NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 4. Donations (후원 내역)
CREATE TABLE IF NOT EXISTS public.donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  amount bigint NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  unit public.org_unit,
  message text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 5. VIP Rewards (VIP 보상)
CREATE TABLE IF NOT EXISTS public.vip_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id) NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  rank int NOT NULL,
  personal_message text,
  dedication_video_url text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 6. VIP Images (VIP 이미지)
CREATE TABLE IF NOT EXISTS public.vip_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reward_id bigint REFERENCES public.vip_rewards(id) ON DELETE CASCADE NOT NULL,
  image_url text NOT NULL,
  title text,
  order_index int DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 7. Signatures (시그니처 - 시그 번호 기반)
CREATE TABLE IF NOT EXISTS public.signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sig_number integer NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  unit public.org_unit NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number)
);

-- 8. Signature Videos (시그 영상 - 멤버별)
CREATE TABLE IF NOT EXISTS public.signature_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signature_id bigint NOT NULL REFERENCES public.signatures(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.organization(id) ON DELETE CASCADE,
  video_url text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signature_videos_sig_member_unique UNIQUE (signature_id, member_id)
);

-- 9. Schedules (일정)
CREATE TABLE IF NOT EXISTS public.schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  unit public.org_unit,
  event_type text CHECK (event_type IN ('broadcast', 'collab', 'event', 'notice', '休')) NOT NULL,
  start_datetime timestamptz NOT NULL,
  end_datetime timestamptz,
  location text,
  is_all_day boolean DEFAULT false NOT NULL,
  color text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 10. Timeline Events (타임라인)
CREATE TABLE IF NOT EXISTS public.timeline_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date date NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  category text,
  season_id bigint REFERENCES public.seasons(id),
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 11. Notices (공지사항)
CREATE TABLE IF NOT EXISTS public.notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  category text CHECK (category IN ('official', 'excel', 'crew')) NOT NULL,
  thumbnail_url text,
  is_pinned boolean DEFAULT false NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  author_id uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 12. Posts (게시글)
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_type text CHECK (board_type IN ('free', 'vip')) NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  like_count bigint DEFAULT 0 NOT NULL,
  comment_count bigint DEFAULT 0 NOT NULL,
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 13. Comments (댓글)
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.comments(id),
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 14. Media Content (Shorts/VOD)
CREATE TABLE IF NOT EXISTS public.media_content (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text CHECK (content_type IN ('shorts', 'vod')) NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  video_url text NOT NULL,
  unit public.org_unit,
  duration int,
  view_count bigint DEFAULT 0 NOT NULL,
  is_featured boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 15. Live Status (라이브 상태)
CREATE TABLE IF NOT EXISTS public.live_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint REFERENCES public.organization(id) NOT NULL,
  platform text CHECK (platform IN ('chzzk', 'twitch', 'youtube', 'pandatv')) NOT NULL,
  stream_url text NOT NULL,
  thumbnail_url text,
  is_live boolean DEFAULT false NOT NULL,
  viewer_count int DEFAULT 0 NOT NULL,
  last_checked timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT live_status_member_platform_unique UNIQUE (member_id, platform)
);

-- 16. Banners (배너)
CREATE TABLE IF NOT EXISTS public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  image_url text NOT NULL,
  link_url text,
  display_order int DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 17. Tribute Guestbook (방명록)
CREATE TABLE IF NOT EXISTS public.tribute_guestbook (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tribute_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  author_name text NOT NULL,
  message text NOT NULL CHECK (char_length(message) <= 500),
  is_member boolean DEFAULT FALSE,
  is_approved boolean DEFAULT TRUE,
  is_deleted boolean DEFAULT FALSE,
  created_at timestamptz DEFAULT NOW() NOT NULL,
  updated_at timestamptz DEFAULT NOW() NOT NULL
);

-- =============================================================
-- PART 3: 트리거 및 함수
-- =============================================================

-- 회원가입 시 profiles 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nickname', split_part(NEW.email, '@', 1)),
    NEW.email,
    'member'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- updated_at 자동 업데이트
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  return new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_updated_at ON public.profiles;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.notices;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.posts;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.posts
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.banners;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.banners
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.tribute_guestbook;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.tribute_guestbook
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 후원금 총액 자동 업데이트
CREATE OR REPLACE FUNCTION public.update_donation_total()
RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation + NEW.amount
      WHERE id = NEW.donor_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation - OLD.amount
      WHERE id = OLD.donor_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation - OLD.amount
      WHERE id = OLD.donor_id;
    END IF;
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation + NEW.amount
      WHERE id = NEW.donor_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_donation_change ON public.donations;
CREATE TRIGGER on_donation_change
  AFTER INSERT OR UPDATE OR DELETE ON public.donations
  FOR EACH ROW EXECUTE PROCEDURE public.update_donation_total();

-- =============================================================
-- PART 4: 헬퍼 함수
-- =============================================================

-- Admin 체크
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('admin', 'superadmin')
  );
$$;

-- Staff 체크 (moderator 포함)
CREATE OR REPLACE FUNCTION public.is_staff(user_id uuid)
RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('moderator', 'admin', 'superadmin')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_admin(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_staff(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 활성 시즌 ID
CREATE OR REPLACE FUNCTION public.get_active_season_id()
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT id FROM public.seasons
  WHERE is_active = true
  ORDER BY start_date DESC NULLS LAST LIMIT 1;
$$;

-- 사용자 랭킹
CREATE OR REPLACE FUNCTION public.get_user_rank(
  p_user_id uuid,
  p_season_id bigint DEFAULT NULL
)
RETURNS TABLE(rank integer, total_amount bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
BEGIN
  IF p_user_id IS NULL THEN RETURN; END IF;

  IF p_season_id IS NULL THEN
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations WHERE donor_id IS NOT NULL GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals WHERE totals.donor_id = p_user_id;
  ELSE
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations
        WHERE donor_id IS NOT NULL AND season_id = p_season_id
        GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals WHERE totals.donor_id = p_user_id;
  END IF;
END;
$$;

-- VIP 체크 (Top 50)
CREATE OR REPLACE FUNCTION public.is_vip_user(user_id uuid)
RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
DECLARE v_rank integer;
BEGIN
  IF user_id IS NULL THEN RETURN FALSE; END IF;

  IF EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('vip', 'moderator', 'admin', 'superadmin')
  ) THEN RETURN TRUE; END IF;

  SELECT rank INTO v_rank FROM public.get_user_rank(user_id, NULL) LIMIT 1;
  RETURN v_rank IS NOT NULL AND v_rank <= 50;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_user_rank(uuid, bigint) TO anon, authenticated;

-- =============================================================
-- PART 5: RLS 정책
-- =============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tribute_guestbook ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "profiles_select" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_update" ON public.profiles FOR UPDATE
  USING (auth.uid() = id OR public.is_staff(auth.uid()));
CREATE POLICY "profiles_insert" ON public.profiles FOR INSERT
  WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "profiles_delete" ON public.profiles FOR DELETE
  USING (public.is_staff(auth.uid()));

-- seasons
CREATE POLICY "seasons_select" ON public.seasons FOR SELECT USING (true);
CREATE POLICY "seasons_all" ON public.seasons FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- organization
CREATE POLICY "org_select" ON public.organization FOR SELECT USING (is_active = true);
CREATE POLICY "org_all" ON public.organization FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- donations
CREATE POLICY "donations_select" ON public.donations FOR SELECT USING (true);
CREATE POLICY "donations_all" ON public.donations FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_rewards
CREATE POLICY "vip_rewards_select" ON public.vip_rewards FOR SELECT
  USING (profile_id = auth.uid() OR public.is_staff(auth.uid()));
CREATE POLICY "vip_rewards_all" ON public.vip_rewards FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_images
CREATE POLICY "vip_images_select" ON public.vip_images FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.vip_rewards
    WHERE vip_rewards.id = vip_images.reward_id
      AND (vip_rewards.profile_id = auth.uid() OR public.is_staff(auth.uid()))
  ));
CREATE POLICY "vip_images_all" ON public.vip_images FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- signatures
CREATE POLICY "signatures_select" ON public.signatures FOR SELECT USING (true);
CREATE POLICY "signatures_all" ON public.signatures FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- signature_videos
CREATE POLICY "sig_videos_select" ON public.signature_videos FOR SELECT USING (true);
CREATE POLICY "sig_videos_all" ON public.signature_videos FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- schedules
CREATE POLICY "schedules_select" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "schedules_all" ON public.schedules FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- timeline_events
CREATE POLICY "timeline_select" ON public.timeline_events FOR SELECT USING (true);
CREATE POLICY "timeline_all" ON public.timeline_events FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- notices
CREATE POLICY "notices_select" ON public.notices FOR SELECT USING (true);
CREATE POLICY "notices_all" ON public.notices FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- posts
CREATE POLICY "posts_select" ON public.posts FOR SELECT
  USING (is_deleted = false AND (board_type = 'free' OR public.is_vip_user(auth.uid())));
CREATE POLICY "posts_insert" ON public.posts FOR INSERT
  WITH CHECK (auth.uid() = author_id AND (board_type = 'free' OR public.is_vip_user(auth.uid())));
CREATE POLICY "posts_update" ON public.posts FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "posts_delete" ON public.posts FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- comments
CREATE POLICY "comments_select" ON public.comments FOR SELECT USING (is_deleted = false);
CREATE POLICY "comments_insert" ON public.comments FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "comments_update" ON public.comments FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "comments_delete" ON public.comments FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- media_content
CREATE POLICY "media_select" ON public.media_content FOR SELECT USING (true);
CREATE POLICY "media_all" ON public.media_content FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- live_status
CREATE POLICY "live_select" ON public.live_status FOR SELECT USING (true);
CREATE POLICY "live_all" ON public.live_status FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- banners
CREATE POLICY "banners_select" ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "banners_all" ON public.banners FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- tribute_guestbook
CREATE POLICY "guestbook_select" ON public.tribute_guestbook FOR SELECT
  USING (is_approved = true AND is_deleted = false);
CREATE POLICY "guestbook_insert" ON public.tribute_guestbook FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "guestbook_update" ON public.tribute_guestbook FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "guestbook_delete" ON public.tribute_guestbook FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- =============================================================
-- PART 6: 인덱스
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_donations_season ON public.donations(season_id);
CREATE INDEX IF NOT EXISTS idx_donations_donor ON public.donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_amount ON public.donations(amount DESC);
CREATE INDEX IF NOT EXISTS idx_posts_board ON public.posts(board_type);
CREATE INDEX IF NOT EXISTS idx_posts_created ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_org_unit ON public.organization(unit);
CREATE INDEX IF NOT EXISTS idx_org_parent ON public.organization(parent_id);
CREATE INDEX IF NOT EXISTS idx_notices_pinned ON public.notices(is_pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_timeline_season ON public.timeline_events(season_id, order_index);
CREATE INDEX IF NOT EXISTS idx_schedules_datetime ON public.schedules(start_datetime);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_donation ON public.profiles(total_donation DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_tribute ON public.tribute_guestbook(tribute_user_id);
CREATE INDEX IF NOT EXISTS idx_guestbook_created ON public.tribute_guestbook(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_banners_active ON public.banners(is_active, display_order) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_signatures_unit ON public.signatures(unit);
CREATE INDEX IF NOT EXISTS idx_signatures_number ON public.signatures(sig_number);
CREATE INDEX IF NOT EXISTS idx_sig_videos_sig ON public.signature_videos(signature_id);
CREATE INDEX IF NOT EXISTS idx_sig_videos_member ON public.signature_videos(member_id);
CREATE INDEX IF NOT EXISTS idx_live_member ON public.live_status(member_id);
CREATE INDEX IF NOT EXISTS idx_live_live ON public.live_status(is_live) WHERE is_live = true;
CREATE INDEX IF NOT EXISTS idx_vip_rewards_season ON public.vip_rewards(season_id);
CREATE INDEX IF NOT EXISTS idx_vip_rewards_rank ON public.vip_rewards(rank);
CREATE INDEX IF NOT EXISTS idx_vip_images_reward ON public.vip_images(reward_id);
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media_content(content_type);

-- =============================================================
-- 완료!
-- =============================================================
