-- Signatures 테이블 재설계
-- 기존: 멤버별 개별 영상 저장
-- 신규: 시그 번호 기반 + signature_videos 테이블로 멤버별 영상 관리

-- 1. 기존 signatures 테이블 백업 (데이터 있으면)
-- CREATE TABLE IF NOT EXISTS signatures_backup AS SELECT * FROM signatures;

-- 2. 기존 테이블 삭제
DROP TABLE IF EXISTS public.signatures CASCADE;

-- 3. 새 signatures 테이블 생성
CREATE TABLE public.signatures (
  id bigint generated by default as identity primary key,
  sig_number integer not null,
  title text not null,
  description text,
  thumbnail_url text,
  unit public.org_unit not null,
  created_at timestamptz default now() not null,

  -- 같은 부서 내 시그 번호 중복 방지
  CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number)
);

-- 4. signature_videos 테이블 생성 (멤버별 영상)
CREATE TABLE public.signature_videos (
  id bigint generated by default as identity primary key,
  signature_id bigint not null references public.signatures(id) on delete cascade,
  member_id bigint not null references public.organization(id) on delete cascade,
  video_url text not null,
  created_at timestamptz default now() not null,

  -- 같은 시그에 같은 멤버 영상 중복 방지
  CONSTRAINT signature_videos_sig_member_unique UNIQUE (signature_id, member_id)
);

-- 5. 인덱스 생성
CREATE INDEX idx_signatures_unit ON public.signatures(unit);
CREATE INDEX idx_signatures_sig_number ON public.signatures(sig_number);
CREATE INDEX idx_signature_videos_signature_id ON public.signature_videos(signature_id);
CREATE INDEX idx_signature_videos_member_id ON public.signature_videos(member_id);

-- 6. RLS 정책
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_videos ENABLE ROW LEVEL SECURITY;

-- signatures: 모두 읽기 가능
CREATE POLICY "signatures_select_all" ON public.signatures
  FOR SELECT USING (true);

-- signatures: admin만 수정 가능
CREATE POLICY "signatures_insert_admin" ON public.signatures
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "signatures_update_admin" ON public.signatures
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "signatures_delete_admin" ON public.signatures
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- signature_videos: 모두 읽기 가능
CREATE POLICY "signature_videos_select_all" ON public.signature_videos
  FOR SELECT USING (true);

-- signature_videos: admin만 수정 가능
CREATE POLICY "signature_videos_insert_admin" ON public.signature_videos
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "signature_videos_update_admin" ON public.signature_videos
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "signature_videos_delete_admin" ON public.signature_videos
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );
