-- =============================================================
-- RG Family: 통합 데이터베이스 스키마
-- Supabase SQL Editor에서 한 번에 실행
-- =============================================================

-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- =============================================================
-- PART 1: 테이블 생성
-- =============================================================

-- Create Enums
DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('member', 'vip', 'moderator', 'admin', 'superadmin');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.org_unit AS ENUM ('excel', 'crew');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 1. Profiles Table (Extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  nickname text not null,
  email text,
  avatar_url text,
  role public.user_role default 'member'::public.user_role not null,
  unit public.org_unit,
  total_donation bigint default 0,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 2. Seasons Table
CREATE TABLE IF NOT EXISTS public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date,
  is_active boolean default false not null,
  created_at timestamptz default now() not null
);

-- 3. Organization Table (Recursive)
CREATE TABLE IF NOT EXISTS public.organization (
  id bigint generated by default as identity primary key,
  unit public.org_unit not null,
  profile_id uuid references public.profiles(id),
  name text not null,
  role text not null,
  position_order int default 0 not null,
  parent_id bigint references public.organization(id),
  image_url text,
  social_links jsonb,
  is_live boolean default false not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null
);

-- 4. Donations Table
CREATE TABLE IF NOT EXISTS public.donations (
  id bigint generated by default as identity primary key,
  donor_id uuid references public.profiles(id),
  donor_name text not null,
  amount bigint not null,
  season_id bigint references public.seasons(id) not null,
  unit public.org_unit,
  message text,
  created_at timestamptz default now() not null
);

-- 5. VIP Rewards
CREATE TABLE IF NOT EXISTS public.vip_rewards (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) not null,
  season_id bigint references public.seasons(id) not null,
  rank int not null,
  personal_message text,
  dedication_video_url text,
  created_at timestamptz default now() not null
);

-- 6. VIP Images (One-to-Many with Rewards)
CREATE TABLE IF NOT EXISTS public.vip_images (
  id bigint generated by default as identity primary key,
  reward_id bigint references public.vip_rewards(id) on delete cascade not null,
  image_url text not null,
  title text,
  order_index int default 0 not null,
  created_at timestamptz default now() not null
);

-- 7. Signatures (Gallery/Media)
CREATE TABLE IF NOT EXISTS public.signatures (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  unit public.org_unit not null,
  member_name text not null,
  media_type text check (media_type in ('video', 'image', 'gif')) not null,
  media_url text not null,
  thumbnail_url text,
  tags text[],
  view_count bigint default 0 not null,
  is_featured boolean default false not null,
  created_at timestamptz default now() not null
);

-- 8. Schedules
CREATE TABLE IF NOT EXISTS public.schedules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  unit public.org_unit,
  event_type text check (event_type in ('broadcast', 'collab', 'event', 'notice', '休')) not null,
  start_datetime timestamptz not null,
  end_datetime timestamptz,
  location text,
  is_all_day boolean default false not null,
  color text,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now() not null
);

-- 9. Timeline Events
CREATE TABLE IF NOT EXISTS public.timeline_events (
  id bigint generated by default as identity primary key,
  event_date date not null,
  title text not null,
  description text,
  image_url text,
  category text,
  season_id bigint references public.seasons(id),
  order_index int default 0,
  created_at timestamptz default now() not null
);

-- 10. Notices
CREATE TABLE IF NOT EXISTS public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text check (category in ('official', 'excel', 'crew')) not null,
  thumbnail_url text,
  is_pinned boolean default false not null,
  view_count bigint default 0 not null,
  author_id uuid references public.profiles(id),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 11. Posts (Community)
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint generated by default as identity primary key,
  board_type text check (board_type in ('free', 'vip')) not null,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) not null,
  view_count bigint default 0 not null,
  like_count bigint default 0 not null,
  comment_count bigint default 0 not null,
  is_anonymous boolean default false not null,
  is_deleted boolean default false not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 12. Comments
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) not null,
  content text not null,
  parent_id bigint references public.comments(id),
  is_deleted boolean default false not null,
  created_at timestamptz default now() not null
);

-- 13. Media Content (Shorts/VODs)
CREATE TABLE IF NOT EXISTS public.media_content (
  id bigint generated by default as identity primary key,
  content_type text check (content_type in ('shorts', 'vod')) not null,
  title text not null,
  description text,
  thumbnail_url text,
  video_url text not null,
  unit public.org_unit,
  duration int,
  view_count bigint default 0 not null,
  is_featured boolean default false not null,
  created_at timestamptz default now() not null
);

-- 14. Live Status
CREATE TABLE IF NOT EXISTS public.live_status (
  id bigint generated by default as identity primary key,
  member_id bigint references public.organization(id) not null,
  platform text check (platform in ('chzzk', 'twitch', 'youtube', 'pandatv')) not null,
  stream_url text not null,
  thumbnail_url text,
  is_live boolean default false not null,
  viewer_count int default 0 not null,
  last_checked timestamptz default now() not null
);

-- 15. Banners
CREATE TABLE IF NOT EXISTS public.banners (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  link_url text,
  display_order int default 0 not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 16. Tribute Guestbook (방명록)
CREATE TABLE IF NOT EXISTS public.tribute_guestbook (
  id bigint generated by default as identity primary key,
  tribute_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  author_name text NOT NULL,
  message text NOT NULL CHECK (char_length(message) <= 500),
  is_member boolean DEFAULT FALSE,
  is_approved boolean DEFAULT TRUE,
  is_deleted boolean DEFAULT FALSE,
  created_at timestamptz DEFAULT NOW() not null,
  updated_at timestamptz DEFAULT NOW() not null
);

-- =============================================================
-- PART 2: 트리거 및 함수
-- =============================================================

-- 회원가입 시 profiles 자동 생성 트리거
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nickname', split_part(NEW.email, '@', 1)),
    NEW.email,
    'member'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Helper function to update updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  return new;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers
DROP TRIGGER IF EXISTS handle_updated_at ON public.profiles;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.notices;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.posts;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.posts
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.banners;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.banners
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.tribute_guestbook;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.tribute_guestbook
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Helper function to update donation totals
CREATE OR REPLACE FUNCTION public.update_donation_total()
RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation + NEW.amount
      WHERE id = NEW.donor_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation - OLD.amount
      WHERE id = OLD.donor_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation - OLD.amount
      WHERE id = OLD.donor_id;
    END IF;
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles
      SET total_donation = total_donation + NEW.amount
      WHERE id = NEW.donor_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_donation_change ON public.donations;
CREATE TRIGGER on_donation_change
  AFTER INSERT OR UPDATE OR DELETE ON public.donations
  FOR EACH ROW EXECUTE PROCEDURE public.update_donation_total();

-- =============================================================
-- PART 3: 헬퍼 함수 (Admin/VIP 체크)
-- =============================================================

-- Admin 체크 함수
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS(
    SELECT 1
    FROM public.profiles
    WHERE id = user_id
      AND role IN ('admin', 'superadmin')
  );
$$;

-- Staff 체크 함수 (moderator 포함)
CREATE OR REPLACE FUNCTION public.is_staff(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS(
    SELECT 1
    FROM public.profiles
    WHERE id = user_id
      AND role IN ('moderator', 'admin', 'superadmin')
  );
$$;

-- No-arg 버전 (기존 코드 호환)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_admin(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_staff(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 활성 시즌 ID 조회
CREATE OR REPLACE FUNCTION public.get_active_season_id()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT id
  FROM public.seasons
  WHERE is_active = true
  ORDER BY start_date DESC NULLS LAST
  LIMIT 1;
$$;

-- 사용자 랭킹 조회
CREATE OR REPLACE FUNCTION public.get_user_rank(
  p_user_id uuid,
  p_season_id bigint DEFAULT NULL
)
RETURNS TABLE(rank integer, total_amount bigint)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN;
  END IF;

  IF p_season_id IS NULL THEN
    RETURN QUERY
      WITH totals AS (
        SELECT
          donor_id,
          sum(amount)::bigint AS total_amount,
          dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations
        WHERE donor_id IS NOT NULL
        GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals
      WHERE totals.donor_id = p_user_id;
  ELSE
    RETURN QUERY
      WITH totals AS (
        SELECT
          donor_id,
          sum(amount)::bigint AS total_amount,
          dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations
        WHERE donor_id IS NOT NULL
          AND season_id = p_season_id
        GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals
      WHERE totals.donor_id = p_user_id;
  END IF;
END;
$$;

-- 활성 시즌 사용자 랭킹 조회
CREATE OR REPLACE FUNCTION public.get_user_rank_active_season(
  p_user_id uuid
)
RETURNS TABLE(rank integer, total_amount bigint, season_id bigint)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_season_id bigint;
BEGIN
  IF p_user_id IS NULL THEN
    RETURN;
  END IF;

  SELECT public.get_active_season_id() INTO v_season_id;
  IF v_season_id IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
    SELECT r.rank, r.total_amount, v_season_id
    FROM public.get_user_rank(p_user_id, v_season_id) AS r;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_user_rank(uuid, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_rank_active_season(uuid) TO anon, authenticated;

-- VIP 사용자 체크
CREATE OR REPLACE FUNCTION public.is_vip_user(user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rank integer;
BEGIN
  IF user_id IS NULL THEN
    RETURN FALSE;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = user_id
      AND role IN ('vip', 'moderator', 'admin', 'superadmin')
  ) THEN
    RETURN TRUE;
  END IF;

  SELECT rank INTO v_rank
  FROM public.get_user_rank(user_id, NULL)
  LIMIT 1;

  RETURN v_rank IS NOT NULL AND v_rank <= 50;
END;
$$;

-- =============================================================
-- PART 4: Row Level Security (RLS) 정책
-- =============================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tribute_guestbook ENABLE ROW LEVEL SECURITY;

-- profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Staff can insert profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins can insert profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins can update any profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can delete profiles" ON public.profiles;

CREATE POLICY "Public profiles are viewable by everyone"
  ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id OR public.is_staff(auth.uid()))
  WITH CHECK (auth.uid() = id OR public.is_staff(auth.uid()));
CREATE POLICY "Staff can insert profiles"
  ON public.profiles FOR INSERT WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "Staff can delete profiles"
  ON public.profiles FOR DELETE USING (public.is_staff(auth.uid()));

-- seasons
DROP POLICY IF EXISTS "Seasons are viewable by everyone" ON public.seasons;
DROP POLICY IF EXISTS "Only admins can modify seasons" ON public.seasons;
DROP POLICY IF EXISTS "Staff can manage seasons" ON public.seasons;
DROP POLICY IF EXISTS "Admins can insert seasons" ON public.seasons;
DROP POLICY IF EXISTS "Admins can update seasons" ON public.seasons;
DROP POLICY IF EXISTS "Admins can delete seasons" ON public.seasons;

CREATE POLICY "Seasons are viewable by everyone"
  ON public.seasons FOR SELECT USING (true);
CREATE POLICY "Staff can manage seasons"
  ON public.seasons FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- organization
DROP POLICY IF EXISTS "Organization is viewable by everyone" ON public.organization;
DROP POLICY IF EXISTS "Only admins can modify organization" ON public.organization;
DROP POLICY IF EXISTS "Staff can manage organization" ON public.organization;
DROP POLICY IF EXISTS "Admins can insert organization" ON public.organization;
DROP POLICY IF EXISTS "Admins can update organization" ON public.organization;
DROP POLICY IF EXISTS "Admins can delete organization" ON public.organization;

CREATE POLICY "Organization is viewable by everyone"
  ON public.organization FOR SELECT USING (is_active = true);
CREATE POLICY "Staff can manage organization"
  ON public.organization FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- donations
DROP POLICY IF EXISTS "Donations are viewable by everyone" ON public.donations;
DROP POLICY IF EXISTS "Only admins can insert donations" ON public.donations;
DROP POLICY IF EXISTS "Staff can manage donations" ON public.donations;
DROP POLICY IF EXISTS "Admins can insert donations" ON public.donations;
DROP POLICY IF EXISTS "Admins can update donations" ON public.donations;
DROP POLICY IF EXISTS "Admins can delete donations" ON public.donations;

CREATE POLICY "Donations are viewable by everyone"
  ON public.donations FOR SELECT USING (true);
CREATE POLICY "Staff can manage donations"
  ON public.donations FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- vip_rewards
DROP POLICY IF EXISTS "VIP rewards visible to owners and admins" ON public.vip_rewards;
DROP POLICY IF EXISTS "VIP Rewards are viewable by everyone" ON public.vip_rewards;
DROP POLICY IF EXISTS "VIP rewards visible to owners and staff" ON public.vip_rewards;
DROP POLICY IF EXISTS "Staff can manage vip_rewards" ON public.vip_rewards;
DROP POLICY IF EXISTS "Admins can insert vip_rewards" ON public.vip_rewards;
DROP POLICY IF EXISTS "Admins can update vip_rewards" ON public.vip_rewards;
DROP POLICY IF EXISTS "Admins can delete vip_rewards" ON public.vip_rewards;

CREATE POLICY "VIP rewards visible to owners and staff"
  ON public.vip_rewards FOR SELECT
  USING (profile_id = auth.uid() OR public.is_staff(auth.uid()));
CREATE POLICY "Staff can manage vip_rewards"
  ON public.vip_rewards FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- vip_images
DROP POLICY IF EXISTS "VIP images visible to reward owners and admins" ON public.vip_images;
DROP POLICY IF EXISTS "VIP Images are viewable by everyone" ON public.vip_images;
DROP POLICY IF EXISTS "VIP images visible to owners and staff" ON public.vip_images;
DROP POLICY IF EXISTS "Staff can manage vip_images" ON public.vip_images;
DROP POLICY IF EXISTS "Admins can insert vip_images" ON public.vip_images;
DROP POLICY IF EXISTS "Admins can update vip_images" ON public.vip_images;
DROP POLICY IF EXISTS "Admins can delete vip_images" ON public.vip_images;

CREATE POLICY "VIP images visible to owners and staff"
  ON public.vip_images FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.vip_rewards
      WHERE vip_rewards.id = vip_images.reward_id
        AND (vip_rewards.profile_id = auth.uid() OR public.is_staff(auth.uid()))
    )
  );
CREATE POLICY "Staff can manage vip_images"
  ON public.vip_images FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- signatures
DROP POLICY IF EXISTS "Signatures are viewable by everyone" ON public.signatures;
DROP POLICY IF EXISTS "Only admins can modify signatures" ON public.signatures;
DROP POLICY IF EXISTS "Staff can manage signatures" ON public.signatures;
DROP POLICY IF EXISTS "Admins can insert signatures" ON public.signatures;
DROP POLICY IF EXISTS "Admins can update signatures" ON public.signatures;
DROP POLICY IF EXISTS "Admins can delete signatures" ON public.signatures;

CREATE POLICY "Signatures are viewable by everyone"
  ON public.signatures FOR SELECT USING (true);
CREATE POLICY "Staff can manage signatures"
  ON public.signatures FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- schedules
DROP POLICY IF EXISTS "Schedules are viewable by everyone" ON public.schedules;
DROP POLICY IF EXISTS "Only admins can modify schedules" ON public.schedules;
DROP POLICY IF EXISTS "Staff can manage schedules" ON public.schedules;
DROP POLICY IF EXISTS "Admins can insert schedules" ON public.schedules;
DROP POLICY IF EXISTS "Admins can update schedules" ON public.schedules;
DROP POLICY IF EXISTS "Admins can delete schedules" ON public.schedules;

CREATE POLICY "Schedules are viewable by everyone"
  ON public.schedules FOR SELECT USING (true);
CREATE POLICY "Staff can manage schedules"
  ON public.schedules FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- timeline_events
DROP POLICY IF EXISTS "Timeline is viewable by everyone" ON public.timeline_events;
DROP POLICY IF EXISTS "Timeline events are viewable by everyone" ON public.timeline_events;
DROP POLICY IF EXISTS "Staff can manage timeline events" ON public.timeline_events;
DROP POLICY IF EXISTS "Admins can insert timeline_events" ON public.timeline_events;
DROP POLICY IF EXISTS "Admins can update timeline_events" ON public.timeline_events;
DROP POLICY IF EXISTS "Admins can delete timeline_events" ON public.timeline_events;

CREATE POLICY "Timeline events are viewable by everyone"
  ON public.timeline_events FOR SELECT USING (true);
CREATE POLICY "Staff can manage timeline events"
  ON public.timeline_events FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- notices
DROP POLICY IF EXISTS "Notices are viewable by everyone" ON public.notices;
DROP POLICY IF EXISTS "Only admins can modify notices" ON public.notices;
DROP POLICY IF EXISTS "Staff can manage notices" ON public.notices;
DROP POLICY IF EXISTS "Admins can insert notices" ON public.notices;
DROP POLICY IF EXISTS "Admins can update notices" ON public.notices;
DROP POLICY IF EXISTS "Admins can delete notices" ON public.notices;

CREATE POLICY "Notices are viewable by everyone"
  ON public.notices FOR SELECT USING (true);
CREATE POLICY "Staff can manage notices"
  ON public.notices FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- posts
DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON public.posts;
DROP POLICY IF EXISTS "Posts are viewable by everyone" ON public.posts;
DROP POLICY IF EXISTS "Users can create posts" ON public.posts;
DROP POLICY IF EXISTS "Authenticated users can create posts" ON public.posts;
DROP POLICY IF EXISTS "Users can update own posts" ON public.posts;
DROP POLICY IF EXISTS "Users can delete own posts" ON public.posts;
DROP POLICY IF EXISTS "Moderators can update any post" ON public.posts;
DROP POLICY IF EXISTS "Moderators can delete any post" ON public.posts;

CREATE POLICY "Posts are viewable by everyone"
  ON public.posts FOR SELECT
  USING (
    is_deleted = false
    AND (board_type = 'free' OR public.is_vip_user(auth.uid()))
  );
CREATE POLICY "Users can create posts"
  ON public.posts FOR INSERT
  WITH CHECK (
    auth.uid() = author_id
    AND (board_type = 'free' OR public.is_vip_user(auth.uid()))
  );
CREATE POLICY "Users can update own posts"
  ON public.posts FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()))
  WITH CHECK (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "Users can delete own posts"
  ON public.posts FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- comments
DROP POLICY IF EXISTS "Comments are viewable by everyone" ON public.comments;
DROP POLICY IF EXISTS "Users can create comments" ON public.comments;
DROP POLICY IF EXISTS "Authenticated users can create comments" ON public.comments;
DROP POLICY IF EXISTS "Users can update own comments" ON public.comments;
DROP POLICY IF EXISTS "Users can delete own comments" ON public.comments;
DROP POLICY IF EXISTS "Moderators can update any comment" ON public.comments;
DROP POLICY IF EXISTS "Moderators can delete any comment" ON public.comments;

CREATE POLICY "Comments are viewable by everyone"
  ON public.comments FOR SELECT USING (is_deleted = false);
CREATE POLICY "Users can create comments"
  ON public.comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users can update own comments"
  ON public.comments FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()))
  WITH CHECK (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "Users can delete own comments"
  ON public.comments FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- media_content
DROP POLICY IF EXISTS "Media is viewable by everyone" ON public.media_content;
DROP POLICY IF EXISTS "Media content is viewable by everyone" ON public.media_content;
DROP POLICY IF EXISTS "Staff can manage media content" ON public.media_content;
DROP POLICY IF EXISTS "Admins can insert media_content" ON public.media_content;
DROP POLICY IF EXISTS "Admins can update media_content" ON public.media_content;
DROP POLICY IF EXISTS "Admins can delete media_content" ON public.media_content;

CREATE POLICY "Media content is viewable by everyone"
  ON public.media_content FOR SELECT USING (true);
CREATE POLICY "Staff can manage media content"
  ON public.media_content FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- live_status
DROP POLICY IF EXISTS "Live status is viewable by everyone" ON public.live_status;
DROP POLICY IF EXISTS "Staff can manage live status" ON public.live_status;
DROP POLICY IF EXISTS "Admins can insert live_status" ON public.live_status;
DROP POLICY IF EXISTS "Admins can update live_status" ON public.live_status;
DROP POLICY IF EXISTS "Admins can delete live_status" ON public.live_status;

CREATE POLICY "Live status is viewable by everyone"
  ON public.live_status FOR SELECT USING (true);
CREATE POLICY "Staff can manage live status"
  ON public.live_status FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- banners
DROP POLICY IF EXISTS "Allow public read access for active banners" ON public.banners;
DROP POLICY IF EXISTS "Allow admin full access to banners" ON public.banners;
DROP POLICY IF EXISTS "Banners are viewable by everyone" ON public.banners;
DROP POLICY IF EXISTS "Staff can manage banners" ON public.banners;
DROP POLICY IF EXISTS "Admins can insert banners" ON public.banners;
DROP POLICY IF EXISTS "Admins can update banners" ON public.banners;
DROP POLICY IF EXISTS "Admins can delete banners" ON public.banners;

CREATE POLICY "Banners are viewable by everyone"
  ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "Staff can manage banners"
  ON public.banners FOR ALL
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

-- tribute_guestbook
DROP POLICY IF EXISTS "guestbook_select_approved" ON public.tribute_guestbook;
DROP POLICY IF EXISTS "guestbook_insert_authenticated" ON public.tribute_guestbook;
DROP POLICY IF EXISTS "guestbook_update_own" ON public.tribute_guestbook;
DROP POLICY IF EXISTS "guestbook_delete_own_or_admin" ON public.tribute_guestbook;
DROP POLICY IF EXISTS "guestbook_admin_all" ON public.tribute_guestbook;

CREATE POLICY "Guestbook entries are viewable when approved"
  ON public.tribute_guestbook FOR SELECT
  USING (is_approved = true AND is_deleted = false);
CREATE POLICY "Users can create guestbook entries"
  ON public.tribute_guestbook FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users can update own guestbook entries"
  ON public.tribute_guestbook FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()))
  WITH CHECK (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "Users can delete own guestbook entries"
  ON public.tribute_guestbook FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- =============================================================
-- PART 5: 인덱스 생성
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_donations_season_id ON public.donations(season_id);
CREATE INDEX IF NOT EXISTS idx_donations_donor_id ON public.donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_amount_desc ON public.donations(amount DESC);
CREATE INDEX IF NOT EXISTS idx_posts_board_type ON public.posts(board_type);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_organization_unit ON public.organization(unit);
CREATE INDEX IF NOT EXISTS idx_organization_parent_id ON public.organization(parent_id);
CREATE INDEX IF NOT EXISTS idx_notices_is_pinned ON public.notices(is_pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_timeline_events_season ON public.timeline_events(season_id, order_index);
CREATE INDEX IF NOT EXISTS idx_schedules_datetime ON public.schedules(start_datetime);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_total_donation ON public.profiles(total_donation DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_tribute_user ON public.tribute_guestbook(tribute_user_id);
CREATE INDEX IF NOT EXISTS idx_guestbook_created_at ON public.tribute_guestbook(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_author ON public.tribute_guestbook(author_id);
CREATE INDEX IF NOT EXISTS idx_banners_active_order ON public.banners(is_active, display_order) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_signatures_unit ON public.signatures(unit);
CREATE INDEX IF NOT EXISTS idx_signatures_member ON public.signatures(member_name);
CREATE INDEX IF NOT EXISTS idx_live_status_member ON public.live_status(member_id);
CREATE INDEX IF NOT EXISTS idx_live_status_live ON public.live_status(is_live) WHERE is_live = true;
CREATE INDEX IF NOT EXISTS idx_vip_rewards_season ON public.vip_rewards(season_id);
CREATE INDEX IF NOT EXISTS idx_vip_rewards_rank ON public.vip_rewards(rank);
CREATE INDEX IF NOT EXISTS idx_vip_images_reward ON public.vip_images(reward_id);
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media_content(content_type);

-- =============================================================
-- PART 6: 샘플 데이터 (시즌)
-- =============================================================

INSERT INTO public.seasons (name, start_date, end_date, is_active) VALUES
  ('시즌 1 - 봄의 시작', '2024-01-01', '2024-03-31', false),
  ('시즌 2 - 여름의 열정', '2024-04-01', '2024-06-30', false),
  ('시즌 3 - 가을의 수확', '2024-07-01', '2024-09-30', false),
  ('시즌 4 - 겨울의 축제', '2024-10-01', NULL, true)
ON CONFLICT DO NOTHING;

-- =============================================================
-- 완료!
-- =============================================================
